require 'simplecov'
SimpleCov.start
require './lib/enigma'
require './lib/offset'
require './lib/key'
require './lib/shift'
require 'pry'
require 'Minitest/pride'
require 'Minitest/autorun'
require 'minitest/stub_any_instance'
